version: '3.8'

services:
  app:
    image: renzzle/github-action:latest
    ports:
      - "9001:9001"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge