name: Deploy to EC2 on Comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker environment
        run: |
          sudo apt-get update
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Installing Docker..."
            sudo apt-get install -y docker.io
          else
            echo "Docker is already installed."
          fi

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ec2-user/
            
            ALL_CONTAINERS=$(docker ps -q)
            if [ -n "$ALL_CONTAINERS" ]; then
              docker stop $ALL_CONTAINERS
              docker rm $ALL_CONTAINERS
            fi
            
            docker-compose down
            docker-compose pull
            docker-compose up -d

      - name: Remove unused Docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker image prune -f
